build:
  nodes:
    builder:

      environment:
        java: java-8-oracle

      deployment:
        -
          commands:
            - command: && echo "OK"
              only_if: $JELASTIC_ENABLED
